"""
ai_analyst.py
=============
Claude-powered AI review layer for voyage performance reports.

Acts as a senior marine engineer / voyage analyst who:
  1. Validates raw data integrity (column headers, data types, value ranges)
  2. Cross-validates computed output against raw data and warranty specs
  3. Returns structured alerts for the user to review

Requires ANTHROPIC_API_KEY in environment (or .env file).
Gracefully skips review if API key is not set or call fails.
"""

from __future__ import annotations

import json
import logging
import os

from config import (
    AI_ANALYST_MODEL,
    AI_ANALYST_MAX_TOKENS,
    AI_ANALYST_TEMPERATURE,
    COL_HEADERS,
    COL,
    WEATHER_BF5_THRESHOLD,
)

logger = logging.getLogger(__name__)


# =============================================================================
# System Prompt
# =============================================================================

SYSTEM_PROMPT = """\
You are a senior marine engineer and voyage performance analyst with 20+ years \
of experience in LNG carrier operations and TCP (Time Charter Party) claims.

You are reviewing a voyage performance report generated by an automated system. \
Your job is to find potential errors, anomalies, and inconsistencies before \
the report is sent to the charterer.

## Your expertise:
- LNG carrier fuel consumption patterns and speed/consumption warranties
- ROB (Remaining on Board) difference methodology for fuel accounting
- Weather exclusion rules (Beaufort Force 5+ threshold)
- Boiler, pilot flame, and GCU (Gas Combustion Unit) consumption norms
- BOR (Boil-Off Rate) expectations for laden vs ballast voyages
- Voyage segmentation due to voyage order revisions

## How you think:
- First validate the raw data structure — are column headers correct? Is data \
in the right columns?
- Then cross-validate every computed number against the raw data
- Ask yourself: "If I were reviewing this before sending to the charterer, \
what would I double-check?"
- When flagging an issue, always provide the specific row/date/value so the \
user can verify quickly

## Rules the automated system uses:
- Rule 1 (Fuel): ROB difference method. Consumed = ROB(DEPARTURE) - ROB(ARRIVAL)
- Rule 2 (Weather): If BF5 hours > {bf5_threshold} hrs → exclude that day's \
fuel proportionally: excluded = (daily_cons / steaming_hrs) × MIN(bf5, steaming)
- Rule 3 (Segments): New segment on voyage order revision (Col BM="yes"), \
next port change (Col J), or fuel mode change (Col K)
- Rule 4 (Auxiliary): Boiler, pilot, GCU extracted and summed per fuel type
- Rule 5 (Warranty): Speed/consumption table interpolation with ageing factors
- Rule A (Speed Anomaly): Flag rows where avg speed < 10% of weighted average
- Rule B (Bunkering): Merge intermediate ARRIVAL/DEPARTURE with same next port

## Your checks (perform ALL of these):

### Phase 1 — Raw Data Integrity:
1. Column header validation — are expected headers present?
2. Data type sanity — numeric columns should be numeric
3. Row structure — DEPARTURE/ARRIVAL in correct sequence
4. Value range — ROB positive, speed 0-25 kts, distance non-negative
5. Missing data — rows with all-zero or all-NaN fuel columns

### Phase 2 — Computed Output Cross-Validation:
6. Fuel rate sanity — daily consumption reasonable for the speed?
7. Distance/speed/time — D ≈ S × T for each segment?
8. ROB consistency — sum of daily ≈ total ROB difference?
9. Weather exclusion proportionality — reasonable vs total?
10. Speed anomalies — actual vs ordered speed deviation explained?
11. Boiler/pilot ranges — within normal bounds?
12. GCU compliance — used above 12 knots?
13. BOR check — actual boil-off vs warranty BOR?
14. Segment boundaries — splits make sense?
15. Data quality — negative consumption, impossible numbers?

## Response format:
Return a JSON array of alert objects. Each alert has:
- "severity": "error" | "warning" | "info"
- "category": short tag (e.g. "fuel_rate", "rob_consistency", "data_integrity")
- "message": concise finding (1-2 sentences)
- "details": supporting data (specific values, rows, dates)

Use "error" for definite problems, "warning" for suspicious items that need \
checking, "info" for observations that may be useful.

Return ONLY the JSON array, no other text.
""".format(bf5_threshold=WEATHER_BF5_THRESHOLD)


# =============================================================================
# Data Preparation
# =============================================================================

def _build_raw_data_context(
    df,
    dep_row: int,
    arr_row: int,
) -> str:
    """Build raw data structure + sample values for integrity checks."""
    lines = ["## RAW DATA STRUCTURE\n"]

    # Column header validation
    lines.append("### Expected vs Actual Column Headers")
    lines.append(f"Total columns in file: {df.shape[1]}")
    lines.append("")

    headers = list(df.columns)
    for key, expected_name in COL_HEADERS.items():
        idx = COL.get(key)
        if idx is not None and idx < len(headers):
            actual = str(headers[idx])
            match = "OK" if actual == expected_name else f"MISMATCH (got: '{actual}')"
            lines.append(f"  {key} (col {idx}): expected '{expected_name}' → {match}")

    # Raw values at DEPARTURE and ARRIVAL rows for critical columns
    lines.append("\n### Critical Raw Values")
    critical_keys = [
        "datetime", "report_type", "voyage_no", "next_port", "fuel_mode",
        "distance", "steaming_hrs", "avg_speed", "ordered_speed",
        "mgo_rob", "lng_rob", "vlsfo_g1_rob", "vlsfo_g2_rob",
        "bf5_hours", "wind_force",
    ]

    for label, row_idx in [("DEPARTURE", dep_row), ("ARRIVAL", arr_row)]:
        lines.append(f"\n  {label} row (index {row_idx}):")
        for key in critical_keys:
            idx = COL.get(key)
            if idx is not None and row_idx < len(df):
                val = df.iloc[row_idx, idx]
                lines.append(f"    {key}: {val}")

    return "\n".join(lines)


def _build_computed_summary(
    voyage_result: dict,
    vessel_config: dict,
) -> str:
    """Build computed output summary for cross-validation."""
    computed = voyage_result["computed"]
    metadata = voyage_result["metadata"]
    auxiliary = voyage_result.get("auxiliary", {})
    segments = computed["segments"]
    totals = computed["totals"]

    lines = ["## COMPUTED OUTPUT\n"]

    # Voyage info
    lines.append("### Voyage Information")
    lines.append(f"  Voyage No: {metadata.get('voyage_no')}")
    lines.append(f"  Type: {metadata.get('voyage_type')}")
    lines.append(f"  Fuel Mode: {metadata.get('fuel_mode')}")
    lines.append(f"  Departure: {metadata.get('dep_datetime')}")
    lines.append(f"  Arrival: {metadata.get('arr_datetime')}")
    lines.append(f"  Discharge Port: {metadata.get('discharge_port')}")

    # Voyage totals
    lines.append("\n### Voyage Totals")
    lines.append(f"  Distance: {totals.get('distance', 0):.1f} nm")
    lines.append(f"  Duration: {totals.get('duration_days', 0):.2f} days")
    lines.append(f"  Avg Speed: {totals.get('actual_avg_speed', 0):.2f} kts")
    lines.append(f"  LNG consumed: {totals.get('lng_consumed', 0):.2f} m³")
    lines.append(f"  MGO consumed: {totals.get('mgo_consumed', 0):.2f} MT")
    lines.append(f"  VLSFO consumed: {totals.get('vlsfo_consumed', 0):.2f} MT")
    lines.append(f"  Net LNG: {totals.get('net_lng', 0):.2f} m³")
    lines.append(f"  Net MGO: {totals.get('net_mgo', 0):.2f} MT")
    lines.append(f"  Net VLSFO: {totals.get('net_vlsfo', 0):.2f} MT")
    lines.append(f"  Weather excl MGO: {totals.get('excl_mgo_weather', 0):.2f} MT")
    lines.append(f"  Weather excl LNG: {totals.get('excl_lng_weather', 0):.2f} m³")
    lines.append(f"  Weather excl VLSFO: {totals.get('excl_vlsfo_weather', 0):.2f} MT")

    # Per-segment data
    lines.append(f"\n### Segments ({len(segments)})")
    for i, seg in enumerate(segments):
        lines.append(f"\n  Segment {i+1}:")
        lines.append(f"    Distance: {seg.get('distance', 0):.1f} nm")
        lines.append(f"    Duration: {seg.get('duration_days', 0):.2f} days")
        lines.append(f"    Instructed Speed: {seg.get('instructed_speed', 0):.1f} kts")
        lines.append(f"    Actual Avg Speed: {seg.get('actual_avg_speed', 0):.2f} kts")
        lines.append(f"    Reference Speed: {seg.get('reference_speed', 0):.2f} kts")
        lines.append(f"    LNG: {seg.get('lng_consumed', 0):.2f} m³")
        lines.append(f"    MGO: {seg.get('mgo_consumed', 0):.2f} MT")
        lines.append(f"    VLSFO: {seg.get('vlsfo_consumed', 0):.2f} MT")
        lines.append(f"    Weather excl hours: {seg.get('excl_weather_hours', 0):.1f}")
        lines.append(f"    Weather excl MGO: {seg.get('excl_mgo_weather', 0):.2f} MT")
        lines.append(f"    Weather excl LNG: {seg.get('excl_lng_weather', 0):.2f} m³")

    # Daily breakdown
    lines.append("\n### Daily Breakdown")
    lines.append("  Date | Dist(nm) | Steam(hrs) | Speed(kts) | MGO_daily | LNG_daily | VLSFO_daily | BF5(hrs)")

    # Get daily_rows from the first segment's raw data
    for seg in segments:
        for dr in seg.get("daily_detail", seg.get("rows", [])):
            dt = str(dr.get("datetime", ""))[:10]
            lines.append(
                f"  {dt} | "
                f"{dr.get('distance', 0):.1f} | "
                f"{dr.get('steaming_hrs', 0):.1f} | "
                f"{dr.get('avg_speed', 0):.1f} | "
                f"{dr.get('mgo_daily', 0):.2f} | "
                f"{dr.get('lng_daily', 0):.2f} | "
                f"{dr.get('vlsfo_daily', 0):.2f} | "
                f"{dr.get('bf5_hours', 0):.1f}"
            )

    # Auxiliary data
    lines.append("\n### Auxiliary Data")
    lines.append(f"  Boiler MGO: {auxiliary.get('mgo_boiler_total', 0):.2f} MT")
    lines.append(f"  Pilot MGO: {auxiliary.get('mgo_pilot_total', 0):.2f} MT")
    lines.append(f"  Boiler VLSFO: {auxiliary.get('vlsfo_boiler_total', 0):.2f} MT")
    lines.append(f"  Pilot VLSFO: {auxiliary.get('vlsfo_pilot_total', 0):.2f} MT")
    lines.append(f"  GCU LNG: {auxiliary.get('gcu_lng_total', 0):.2f} m³")
    lines.append(f"  GCU used: {auxiliary.get('gcu_used', False)}")
    lines.append(f"  Cargo Density: {auxiliary.get('cargo_density')}")
    lines.append(f"  LCV: {auxiliary.get('lcv')}")
    lines.append(f"  Reliq Hours: {auxiliary.get('reliq_total_hours', 0):.1f}")

    # Vessel warranty table
    lines.append("\n### Vessel Warranty Speed/Consumption Table")
    sct = vessel_config.get("speed_consumption_table", {})
    lines.append("  Speed(kts) | Laden_Gas(MT/d) | Laden_Pilot(MT/d) | Ballast_Gas(MT/d) | Ballast_Pilot(MT/d)")
    for speed in sorted(sct.keys(), reverse=True):
        vals = sct[speed]
        lines.append(f"  {speed:.1f} | {vals[0]:.1f} | {vals[1]:.1f} | {vals[2]:.1f} | {vals[3]:.1f}")

    lines.append(f"\n  BOR Laden: {vessel_config.get('bor_laden_pct', 0)}%/day")
    lines.append(f"  BOR Ballast: {vessel_config.get('bor_ballast_pct', 0)}%/day")
    lines.append(f"  Gross Capacity: {vessel_config.get('gross_capacity_cbm', 0):.2f} cbm")
    lines.append(f"  FOE Factor: {vessel_config.get('foe_factor', 0)}")

    # Speed anomalies
    anomalies = computed.get("speed_anomalies", [])
    if anomalies:
        lines.append(f"\n### Speed Anomalies Detected ({len(anomalies)})")
        for a in anomalies:
            lines.append(
                f"  {str(a['datetime'])[:16]}: speed={a['avg_speed']:.1f} kts, "
                f"weighted_avg={a['weighted_avg']:.1f} kts"
            )

    return "\n".join(lines)


# =============================================================================
# AI Review
# =============================================================================

def review_voyage(
    df,
    voyage_result: dict,
    vessel_config: dict,
) -> list[dict]:
    """
    Send voyage data to Claude for expert review.

    Parameters
    ----------
    df             : raw DataFrame
    voyage_result  : dict with "computed", "metadata", "auxiliary"
    vessel_config  : vessel configuration dict

    Returns
    -------
    list[dict] — alerts, each with severity/category/message/details.
    Returns empty list if API key is missing or call fails.
    """
    api_key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not api_key:
        logger.warning(
            "ANTHROPIC_API_KEY not set — skipping AI review. "
            "Set it in .env to enable the AI analyst."
        )
        return []

    try:
        import anthropic
    except ImportError:
        logger.warning(
            "anthropic package not installed — skipping AI review. "
            "Run: pip install anthropic"
        )
        return []

    # Build context
    metadata = voyage_result["metadata"]
    dep_row = voyage_result["computed"]["totals"].get("dep_row")
    arr_row = voyage_result["computed"]["totals"].get("arr_row")

    # Fallback: get dep/arr rows from metadata if not in totals
    if dep_row is None:
        # Try to parse from segment_info
        seg_info = voyage_result["computed"].get("segment_info", [])
        if seg_info:
            dep_row = seg_info[0].get("start_row_idx", 0)
            arr_row = seg_info[-1].get("end_row_idx", len(df) - 1)

    # Build the data context for Claude
    raw_context = ""
    if dep_row is not None and arr_row is not None:
        raw_context = _build_raw_data_context(df, dep_row, arr_row)

    computed_summary = _build_computed_summary(voyage_result, vessel_config)

    user_message = (
        f"Please review this voyage performance report for Voyage "
        f"{metadata.get('voyage_no', 'Unknown')} "
        f"({metadata.get('voyage_type', '')}).\n\n"
        f"{raw_context}\n\n{computed_summary}"
    )

    # Call Claude API
    try:
        client = anthropic.Anthropic(api_key=api_key)
        response = client.messages.create(
            model=AI_ANALYST_MODEL,
            max_tokens=AI_ANALYST_MAX_TOKENS,
            temperature=AI_ANALYST_TEMPERATURE,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_message}],
        )

        # Parse response
        content = response.content[0].text.strip()

        # Handle markdown code blocks
        if content.startswith("```"):
            content = content.split("\n", 1)[1] if "\n" in content else content
            if content.endswith("```"):
                content = content[:-3].strip()

        alerts = json.loads(content)

        if not isinstance(alerts, list):
            logger.warning("AI analyst returned non-list response: %s", type(alerts))
            return []

        logger.info(
            "AI review complete: %d alert(s) for Voyage %s",
            len(alerts), metadata.get("voyage_no"),
        )
        return alerts

    except json.JSONDecodeError as e:
        logger.warning("AI analyst returned invalid JSON: %s", e)
        return []
    except Exception as e:
        logger.warning("AI review failed: %s", e)
        return []
